spring:
  redis:
    database: 10
    host: 10.110.84.138
    port: 6931
    password: langchaoTest6530

    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: -1    # 连接池最大阻塞等待时间 ms（使用负值表示没有限制）

redisson:
  # 单机
  address: 10.110.84.138:6931
  password: langchaoTest6530
  database: 10

#  # 哨兵集群
#  master-name: mymaster
#  password: langchaoTest6530
#  sentinel-addresses:
#    - 10.47.91.83:26379
#    - 10.47.91.83:26380
#    - 10.47.91.83:26381



